---
apiVersion: apps/v1
kind: deployment
metadata:
  name: tomcat-deployment
  labels:
    type: appserver
    author: clauddy
spec:
  replicas: 2
  seclector:
   matchLabels:
    type: appserver
  template:
   metadata:
    name: tomcat-pod
    labels:
     type: appserver
   spec:
    containers:
     -name: mytomcat
      image: tomee



